### ISSUE TITLE
Coloring Volcano by selected gene while keeping up and down colors

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEEu#109]
Hi! 
I see the Volcano plot is colored by up and down genes when Color by is "None". I would like to color by Feature Name sometimes but keeping the up and down genes colored. Could you please point me out on how to implemment this?

Thanks!

**Comment by LTLA** [comment]
IIRC this probably won't be easy. The up/down coloring only affects the default `None` color-by status; any user request to use non-`None` color will override the default coloring. This is, on the whole, desirable for most users as it is hard to distinguish between the pink-ish up color and the default red color used for highlighting the selected feature.

**Comment by kevinrue** [comment]
Closing this as no immediate plan to implement
