### ISSUE TITLE
Comments on ReducedDimensionHexPlot

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEEu#57]
- ~Is the `.cacheCommonInfo()` method really necessary?~
- Use this class to determine which dot plot creation utilities need to be added to **iSEE**. Obvious candidates are utilities to set font size or to add the `coord_cartesian` layer.
- `.addFacets` should probably operate more like `.addMultiSelectionPlotCommands` in terms of taking a `commands=` and slapping a `+` to the end to modify the `ggplot` construction.

**Comment by kevinrue** [comment]
Closed as copied to iSEEhex
