### ISSUE TITLE
Need to actually import stat_summary_hex

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEEu#68]
Currently ReducedDimensionHexPlot fails because it's not actually imported. `R CMD check` doesn't detect it because of we wrapped it in a string.

**Comment by kevinrue** [comment]
Ok. For the time being, running `library(ggplot2)` in the session before launching the app gives a workaround.

**Comment by LTLA** [comment]
Dammit. Got the "12 hours" confused with the issue number. Oh well, fixed by bd453da17292d45418742cd5c32dfbab74d7f9ee.

Note that this ended up being pretty hairy. Importing in the **iSEEu** namespace was not sufficient as the commands are evaluated in the **iSEE** namespace where those functions are not available. This meant that an explicit `ggplot2::` prefix was necessary for these functions; the same applies for other panel types. 

We should add this to the instructions in `.generateTable`, `.generateOutput` and `.generateDotPlot` back in **iSEE**.
