### ISSUE TITLE
Default interface simplification?

### ISSUE THREAD

**Issue by robertamezquita** [iSEE/iSEEu#7]
Working with several biological collaborators using iSEE, a few things came up as must-haves to make iSEE a part of their regular routine. One issue that came up was the default interface was a bit intimidating with the sheer number of panels that came up. 

Most of the biological collaborators come from using 10X's software, the Loupe Browser (https://support.10xgenomics.com/single-cell-gene-expression/software/visualization/latest/what-is-loupe-cell-browser), which presents a single panel on start-up. I could see a similar tact here with one of the dimreds being loaded (anything matching TSNE/UMAP since thats always the first go to, or the first dimred otherwise).

Maybe this would also help slightly with the long load time as well if only one panel is loaded at start-up?

**Comment by kevinrue** [comment]
Seems like this was answered above
