### ISSUE TITLE
Disable merge requirements

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEEu#9]
Either disable merge requirements or pull **iSEE** from the GitHub master, otherwise the development cycle is too long if we have to wait for new API points to become available in **iSEE**.

**Comment by kevinrue** [comment]
Administrators can now "force merge" even when requirements fail.

That said, I expect this development cycle issue to be really just a short term thing while the early stages of `iSEEu` developments identify the relevant `iSEE` updates.

That kind of issue should be less frequent after the first few `iSEEu` panels are added, and essentially disappear over time.
